### ISSUE TITLE
Cargo features from config

### ISSUE THREAD

**Issue by maccesch** [rwasm/vite-plugin-rsw#22]
During development we have quite a few handy but slow debugging features enabled. I'd like to activate them from the config.

It would be great to have a `features` key in the config that controls which features for a crate are active.

In addition to future proof this it probably makes sense to implement an additional general purpose key like `extraArguments` or sth like this that allows to add arbitrary arguments to add to the call to `cargo build`.

**Comment by lencx** [comment]
To build production environment code, please use [rsw-node](https://github.com/lencx/rsw-node), [--release](https://rustwasm.github.io/wasm-pack/book/commands/build.html#profile) is not recommended in development mode.

`vite-plugin-rsw` is currently not implemented, the next version can support:
- [target](https://rustwasm.github.io/wasm-pack/book/commands/build.html#target)
- [mode](https://rustwasm.github.io/wasm-pack/book/commands/build.html#mode)
- [extra options](https://rustwasm.github.io/wasm-pack/book/commands/build.html#extra-options)

[RswCrateOptions](https://github.com/lencx/vite-plugin-rsw/blob/bb95373d3b/src/types.ts#L7-L11)
```ts
export type RswCrateOptions = {
  // support `--out-name` and `scope`
  name: string;
  // `--out-dir`
  outDir?: string;
  // defalut: 'web'
  target?: 'bundler' | 'web' | 'nodejs' | 'deno' | 'no-modules';
  // no default value 
  mode?: 'no-install' | 'normal';
  // extra options
  args?: string[];
}
```

**Comment by lencx** [comment]
@maccesch  install the `v1.10.0` version to try the [plugin options](https://github.com/lencx/vite-plugin-rsw#plugin-options).
