### ISSUE TITLE
run 'vite' and  'rsw && vite build'  should not change the yarn.lock

### ISSUE THREAD

**Issue by deftsp** [rwasm/vite-plugin-rsw#27]
The code has been committed. Running 'rsw && vite build'  changed the `yarn.lock`.

It's happened after upgrading the `vite-plugin-rsw` and `rsw-node`

```
modified   yarn.lock
@@ -1238,8 +1238,8 @@
   optionalDependencies:
     "fsevents" "~2.3.2"
 
-"foobar@file:foobar/pkg":
-  "resolved" "file:foobar/pkg"
+"foobar@file:.rsw/crates/foobar/pkg":
+  "resolved" "file:.rsw/crates/foobar/pkg"
   "version" "0.1.5"
 
 "color-convert@^1.9.0":
```

Current version
```
"vite": "2.7.4",
"vite-plugin-pwa": "^0.11.12",
"vite-plugin-rsw": "^1.10.2",
```

**Comment by lencx** [comment]
At present, I have not thought of a good solution. Welcome to communicate.

`yarn build` needs to use `rsw-node`, `.rsw/crates/` will be the root path of the build. When executing `yarn` related commands, `yarn.lock` will be rewritten, you can try to execute `npm run build`.

```json
{
  "scripts": {
    "build": "rsw && vite build"
  }
}
```

**Comment by deftsp** [comment]
What about the previous version?  I used them without this problem until upgrading the `node` from v12 to v16 then reinstalling `rsw-node`.

**Comment by lencx** [comment]
`v0.1.2` may be the version you used before.

**Comment by deftsp** [comment]
` "rsw-node": "0.1.2"`  +   `"vite-plugin-rsw": "^1.10.2"`  works fine.  :)
