### ISSUE TITLE
Do not remove the whole generated package on recompile

### ISSUE THREAD

**Issue by dmtrKovalenko** [rwasm/vite-plugin-rsw#28]
Right now when I update the dependency of the wasm package the whole generated package is deleted. This leads to this weird behavior when on each saves an error model appears and disappears. 

https://user-images.githubusercontent.com/16926049/151696953-3c492b79-7678-4507-a244-78437b81b3c6.mov

 Potential fix: override the package instead of removing, at least with a flag

**Comment by lencx** [comment]
Hi, you can try to export `npm package` instead of relative path, `vite-plugin-rsw` installs `rust crate` using `npm link`.

### Usage

```tsx
// video-wasm-binding: package name
import * as videoWasmBinding from 'video-wasm-binding';

// 1. load wasm file
videoWasmBinding.init();
// 2. other methods
videoWasmBinding.xx()
````

### Example

https://github.com/lencx/learn-wasm/blob/main/src/views/chasm.tsx
https://github.com/lencx/learn-wasm/blob/main/src/views/game_of_life.tsx
