### ISSUE TITLE
yarn rsw

### ISSUE THREAD

**Issue by cz-97** [rwasm/vite-plugin-rsw#30]
I created a Vite project and followed the readme of the repo,then an error occurred when I did 'yarn rsw init'
```
Error: spawnSync PROJECT\node_modules\binary-install\bin\rsw.exe UNKNOWN

```

**Comment by lencx** [comment]
You can try the `rsw` command after installing it globally.

```bash
# Node.js
npm i -g @rsw/cli

# Or Rust
cargo install rsw
```
