### ISSUE TITLE
Broken on Windows 11: "rsw.exe is not compatible with the version of Windows you're running."

### ISSUE THREAD

**Issue by ConnorJamesLow** [rwasm/vite-plugin-rsw#33]
**Describe the bug**
When running `npx rsw init` (or `rsw init`) I get the following error:

```txt
This version of C:\Users\conno\AppData\Roaming\nvm\v16.13.1\node_modules\@rsw\cli\bin\rsw.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

**To Reproduce**
1. Install rsw cli via npm: `npm i -g @rsw/cli`.
2. Run `npx rsw init` to initialize the toml.
3. Error.

**Expected behavior**
The rsw.toml file is initialized.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari]: N/A

**Additional context**
<details>
<summary>
Windows specs
</summary

Edition	Windows 11 Home
Version	22H2
Installed on	‎5/‎20/‎2022
OS build	22621.1
Serial number	PF1L162W
Experience	Windows Feature Experience Pack 1000.22632.1000.0
</details>

npm v8.12.1  

node v16.13.1

**Comment by lencx** [comment]
There is a problem with npm pulling binary files, and I don't know how to deal with it for the time being. If you have a good way, you are welcome to contribute PR.

Project: [rsw-rs](https://github.com/rwasm/rsw-rs/tree/main/npm)
Solution: Can be installed with `cargo install rsw`.
