### ISSUE TITLE
CssSyntaxError during build

### ISSUE THREAD

**Issue by tcastelly** [rwasm/vite-plugin-rsw#34]
**Describe the bug**
Enable the plugin throw an error during the build
```
error during build:
CssSyntaxError: /home/tcy/documents/dev/workspaces/tauri/vue-tauri-vite/src/App.vue:12:3: Unknown word
```

**To Reproduce**
1. git clone https://github.com/tcastelly/vue-tauri-vite
2. npm ci
3. npm run build

**Expected behavior**
Build

**Desktop (please complete the following information):**
 - OS: Arch Gnu Linux
 - Browser chromium

**Additional context**
Disable the plugin, the build works.

**Comment by lencx** [comment]
The latest version of `vite-plugin-rsw` runs only in development mode and does not require `rsw-node` to be installed, it is deprecated. Please install [rsw-rs](https://github.com/rwasm/rsw-rs).

```bash
cargo install rsw
````

Usage can refer to [OhMyBox](https://github.com/lencx/OhMyBox).

`package.json`

```json
{
  "scripts": {
    "dev": "vite",
    "build": "rsw build && tsc && vite build",
    "preview": "vite preview",
    "tauri": "tauri",
    "rsw": "rsw"
  }
}
```

**Comment by tcastelly** [comment]
thank you very much for your help.
